export { default as adBlock } from './adBlock'
export { default as addBehavior } from './addBehavior'
export { default as audio } from './audio'
export {
  default as availableScreenResolution
} from './availableScreenResolution'
export { default as canvas } from './canvas'
export { default as colorDepth } from './colorDepth'
export { default as cpuClass } from './cpuClass'
export { default as deviceMemory } from './deviceMemory'
export { default as doNotTrack } from './doNotTrack'
export { default as enumerateDevices } from './enumerateDevices'
export { default as fonts } from './fonts'
export { default as fontsFlash } from './fontsFlash'
export { default as hardwareConcurrency } from './hardwareConcurrency'
export { default as hasLiedBrowser } from './hasLiedBrowser'
export { default as hasLiedLanguages } from './hasLiedLanguages'
export { default as hasLiedOs } from './hasLiedOs'
export { default as hasLiedResolution } from './hasLiedResolution'
export { default as indexedDb } from './indexedDb'
export { default as language } from './language'
export { default as localStorage } from './localStorage'
export { default as openDatabase } from './openDatabase'
export { default as pixelRatio } from './pixelRatio'
export { default as platform } from './platform'
export { default as plugins } from './plugins'
export { default as screenResolution } from './screenResolution'
export { default as sessionStorage } from './sessionStorage'
export { default as timezone } from './timezone'
export { default as timezoneOffset } from './timezoneOffset'
export { default as touchSupport } from './touchSupport'
export { default as userAgent } from './userAgent'
export { default as webdriver } from './webdriver'
export { default as webgl } from './webgl'
export { default as webglVendorAndRenderer } from './webglVendorAndRenderer'

export { default as recommended } from './recommended'
